server:
  port: 80

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password: password
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/exemplo
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect