server:
  port: 80

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:password}
    driverClassName: org.h2.Driver
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:db}
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect