server:
  port: 80

spring:
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true